# Generated by Django 6.0.3 on 2026-05-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user_auth.user",),
        ),
    ]
