# Generated by Django 6.0.3 on 2026-04-05 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0003_alter_company_options"),
        ("driver", "0001_created_driver_model"),
        ("vehicle", "0012_created_ride_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("all_day", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "ride_type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Line"),
                            (2, "Transfer"),
                            (3, "Excursion"),
                            (4, "Round Tour"),
                        ],
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_date", models.DateField(blank=True)),
                ("end_date", models.DateField(blank=True)),
                ("start_time", models.TimeField(blank=True)),
                ("end_time", models.TimeField(blank=True)),
                ("start_location", models.CharField(blank=True, max_length=255)),
                ("end_location", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides",
                        to="company.company",
                    ),
                ),
                ("drivers", models.ManyToManyField(blank=True, to="driver.driver")),
                ("vehicles", models.ManyToManyField(blank=True, to="vehicle.vehicle")),
            ],
            options={
                "verbose_name_plural": "Ride",
            },
        ),
    ]
