# Generated by Django 6.0.3 on 2026-05-05 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agency", "0001_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("start_location", models.CharField(blank=True, max_length=255)),
                ("end_location", models.CharField(blank=True, max_length=255)),
                ("is_all_day", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "ride_type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Line"),
                            (2, "Transfer"),
                            (3, "Excursion"),
                            (4, "Round Tour"),
                        ],
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "agency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rides",
                        to="agency.agency",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ride",
            },
        ),
    ]
