# Generated by Django 6.0.3 on 2026-05-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("driver", "0002_initial"),
        ("guide", "0001_initial"),
        ("ride", "0001_initial"),
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="drivers",
            field=models.ManyToManyField(
                blank=True, related_name="drivers_rides", to="driver.driver"
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="guides",
            field=models.ManyToManyField(
                blank=True, related_name="guides_rides", to="guide.guide"
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="vehicles",
            field=models.ManyToManyField(
                blank=True, related_name="vehicles_rides", to="vehicle.vehicle"
            ),
        ),
    ]
