# Generated by Django 6.0.3 on 2026-04-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0001_created_ride_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
