# Generated by Django 6.0.3 on 2026-05-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0002_initial"),
        ("ride", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_rides",
                to="driver.driver",
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
