# Generated by Django 6.0.3 on 2026-04-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0002_null_to_date_fiels"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ride",
            old_name="all_day",
            new_name="is_all_day",
        ),
    ]
