# Generated by Django 6.0.3 on 2026-05-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0002_initial"),
        ("ride", "0003_ride_confirmed_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="confirmed_by",
        ),
        migrations.AddField(
            model_name="ride",
            name="confirmed_by",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="confirmed_rides",
                to="driver.driver",
            ),
        ),
    ]
