# Generated by Django 6.0.3 on 2026-04-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0001_created_driver_model"),
        ("ride", "0003_is_all_day"),
        ("vehicle", "0012_created_ride_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="drivers",
            field=models.ManyToManyField(
                blank=True, related_name="rides", to="driver.driver"
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="vehicles",
            field=models.ManyToManyField(
                blank=True, related_name="rides", to="vehicle.vehicle"
            ),
        ),
    ]
