# Generated by Django 6.0.3 on 2026-05-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0004_ride_confirmed_by_many_to_many"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="is_confirmed",
        ),
    ]
