# Generated by Django 6.0.3 on 2026-04-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0001_initial"),
        ("ride", "0004_alter_ride_drivers_alter_ride_vehicles"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="guides",
            field=models.ManyToManyField(
                blank=True, related_name="rides", to="guide.guide"
            ),
        ),
    ]
