# Generated by Django 6.0.3 on 2026-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0002_alter_agency_options"),
        ("ride", "0005_guides_many_to_many"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="agencies",
            field=models.ManyToManyField(
                blank=True, related_name="rides", to="agency.agency"
            ),
        ),
    ]
