# Generated by Django 6.0.3 on 2026-05-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0005_removed_is_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
