# Generated by Django 6.0.3 on 2026-05-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0002_initial"),
        ("ride", "0006_is_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="confirmed_by",
            field=models.ManyToManyField(
                blank=True, related_name="confirmed_rides", to="driver.driver"
            ),
        ),
    ]
