# Generated by Django 6.0.3 on 2026-04-11 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0005_added_ceo_and_contact_person_fields"),
        ("ride", "0006_ride_agencies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="agencies",
        ),
        migrations.AddField(
            model_name="ride",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="agency.agency",
            ),
        ),
    ]
