# Generated by Django 6.0.3 on 2026-05-05 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0010_agency_documents_agency"),
        ("ride", "0007_agency_to_foreign_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rides",
                to="agency.agency",
            ),
        ),
    ]
