services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: buspilot-backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/code
      - ./backend/media:/code/media
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
      - DATABASE_URL=postgresql://radomir:biljana4@192.168.1.10:5432/buspilot
    networks:
      - app-network

  testing:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: buspilot-testing
    volumes:
      - ./backend:/code
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=backend.settings.test
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
