FROM python:3.14-slim

WORKDIR /code

COPY requirements requirements

RUN pip install --no-cache-dir -r requirements/test.txt

COPY . .

CMD ["sh", "-c", "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:1337"]
