FROM python:3.14-slim

WORKDIR /code

COPY requirements requirements

RUN python3 -m pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements/dev.txt

COPY . .

CMD ["sh", "-c", "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"]
