# Generated by Django 6.0.3 on 2026-05-05 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("mobile_number", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=100)),
                ("website", models.CharField(blank=True, max_length=255)),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Tax Identification Number (PIB)",
                        max_length=100,
                    ),
                ),
                (
                    "vat",
                    models.CharField(
                        blank=True, help_text="Value Added Tax (PDV)", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company",
            },
        ),
        migrations.CreateModel(
            name="CompanyAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(blank=True, max_length=255)),
                ("country_code", models.CharField(blank=True, max_length=3)),
                ("post_code", models.CharField(blank=True, max_length=100)),
                ("state_province", models.CharField(blank=True, max_length=255)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("street_number", models.CharField(blank=True, max_length=10)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company Address",
            },
        ),
    ]
