# Generated by Django 6.0.3 on 2026-03-27 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="vat",
            field=models.CharField(
                blank=True, help_text="Value Added Tax (PDV)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="companyaddress",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="company.company",
            ),
        ),
    ]
