# Generated by Django 6.0.3 on 2026-03-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_company_vat_alter_companyaddress_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "Company"},
        ),
    ]
