# Generated by Django 6.0.3 on 2026-05-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_company_documents"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompanyDocuments",
            new_name="CompanyDocument",
        ),
    ]
