# Generated by Django 6.0.3 on 2026-04-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_company_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyaddress",
            options={"verbose_name_plural": "Company Address"},
        ),
    ]
