# Generated by Django 6.0.3 on 2026-06-09 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_remove_s_from_model_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companydocument",
            options={"ordering": ["expiring_at"]},
        ),
        migrations.AlterField(
            model_name="companydocument",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_documents",
                to="company.company",
            ),
        ),
    ]
