# Generated by Django 6.0.3 on 2026-06-10 13:47

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_defect_vehicle_cant_be_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyaddress",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
