# Generated by Django 6.0.3 on 2026-05-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defect", "0001_defect_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="defect",
            name="is_fixed",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
