# Generated by Django 6.0.3 on 2026-05-19 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defect", "0002_is_fixed"),
    ]

    operations = [
        migrations.AddField(
            model_name="defect",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="defect",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
