# Generated by Django 6.0.3 on 2026-05-19 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defect", "0003_created_updated_timestamp"),
        ("driver", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="defect",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_defects",
                to="driver.driver",
            ),
        ),
    ]
