# Generated by Django 6.0.3 on 2026-05-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("defect", "0004_reported_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defect",
            options={"ordering": ["-created_at"]},
        ),
    ]
