# Generated by Django 6.0.3 on 2026-06-09 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defect", "0005_ride_confirmed_by"),
        ("vehicle", "0002_defect_vehicle_cant_be_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defect",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="defects",
                to="vehicle.vehicle",
            ),
        ),
    ]
