# Generated by Django 6.0.3 on 2026-04-10 14:58

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0003_alter_company_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=100)),
                ("mobile_phone_number", models.CharField(blank=True, max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agencies",
                        to="company.company",
                    ),
                ),
            ],
        ),
    ]
