# Generated by Django 6.0.3 on 2026-05-05 13:16

import common.models
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_header_color", models.CharField(blank=True, max_length=20)),
                ("ceo", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=50)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=100)),
                ("mobile_phone_number", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agencies",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agency",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AgencyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("document_type", models.CharField(blank=True, max_length=255)),
                ("expiring_at", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="agency/documents",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "docx",
                                    "txt",
                                    "xlsx",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="agency.agency",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_documents",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, common.models.DocumentManager),
            managers=[
                ("expiring", django.db.models.manager.Manager()),
            ],
        ),
    ]
