# Generated by Django 6.0.3 on 2026-06-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agencydocument",
            options={"ordering": ["expiring_at"]},
        ),
    ]
