# Generated by Django 6.0.3 on 2026-04-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_created_agency_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agency",
            options={"verbose_name_plural": "Agency"},
        ),
    ]
