# Generated by Django 6.0.3 on 2026-04-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0002_alter_agency_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="card_header_color",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
