# Generated by Django 6.0.3 on 2026-04-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0003_created_ui_style_abstract_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
