# Generated by Django 6.0.3 on 2026-04-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0004_added_city_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="ceo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="agency",
            name="contact_person",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
