# Generated by Django 6.0.3 on 2026-04-23 07:54

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0005_added_ceo_and_contact_person_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agency",
            options={"ordering": ("name",), "verbose_name_plural": "Agency"},
        ),
        migrations.AlterField(
            model_name="agency",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
