# Generated by Django 6.0.3 on 2026-05-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0007_agency_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
