# Generated by Django 6.0.3 on 2026-05-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0009_agency_documents"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agencydocument",
            old_name="driver",
            new_name="agency",
        ),
    ]
