# Generated by Django 6.0.3 on 2026-06-10 13:47

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestDemo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField()),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
