# Generated by Django 6.0.3 on 2026-06-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requestdemo", "0001_request_demo_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requestdemo",
            options={"verbose_name_plural": "Request Demo"},
        ),
        migrations.AddField(
            model_name="requestdemo",
            name="contact_number",
            field=models.CharField(default=3024),
            preserve_default=False,
        ),
    ]
