# Generated by Django 6.0.3 on 2026-07-11 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requestdemo", "0002_added_contact_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestdemo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestdemo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
