# Generated by Django 6.0.3 on 2026-03-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("chassis_number", models.CharField(blank=True, max_length=100)),
                ("engine_number", models.CharField(blank=True, max_length=100)),
                ("horse_power", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("vehicle_type", models.CharField(blank=True, max_length=100)),
                (
                    "weight",
                    models.CharField(
                        blank=True, help_text="weight in KG", max_length=100
                    ),
                ),
            ],
        ),
    ]
