# Generated by Django 6.0.3 on 2026-05-05 13:16

import common.models
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("driver", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("chassis_number", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(blank=True, max_length=100)),
                ("engine_number", models.CharField(blank=True, max_length=100)),
                ("horse_power", models.CharField(blank=True, max_length=100)),
                ("licence_number", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("number_of_seats", models.CharField(blank=True, max_length=20)),
                ("year_of_production", models.CharField(blank=True, max_length=100)),
                (
                    "vehicle_type",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Car"),
                            (2, "Van"),
                            (3, "Mini Bus"),
                            (5, "Midi Bus"),
                            (4, "Bus"),
                        ],
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True, help_text="weight in KG", max_length=100
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="company.company",
                    ),
                ),
                (
                    "driver",
                    models.ManyToManyField(
                        blank=True, related_name="vehicles", to="driver.driver"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("document_type", models.CharField(blank=True, max_length=255)),
                ("expiring_at", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="vehicle/documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "docx",
                                    "txt",
                                    "xlsx",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_documents",
                        to="company.company",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vehicle.vehicle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, common.models.DocumentManager),
            managers=[
                ("expiring", django.db.models.manager.Manager()),
            ],
        ),
    ]
