# Generated by Django 6.0.3 on 2026-03-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_company_vat_alter_companyaddress_company"),
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="year_of_production",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
