# Generated by Django 6.0.3 on 2026-03-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0002_vehicle_company_vehicle_year_of_production"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="number_of_seats",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
