# Generated by Django 6.0.3 on 2026-03-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0003_vehicle_number_of_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="color",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="license_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[("Bus", "Bus"), ("Van", "Van"), ("Car", "Car")],
                max_length=100,
            ),
        ),
    ]
