# Generated by Django 6.0.3 on 2026-03-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0004_vehicle_color_vehicle_license_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="license_number",
            new_name="licence_number",
        ),
    ]
