# Generated by Django 6.0.3 on 2026-03-30 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0005_rename_license_number_vehicle_licence_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="vehicle/documents/")),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicle.vehicle",
                    ),
                ),
            ],
        ),
    ]
