# Generated by Django 6.0.3 on 2026-03-30 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0006_created_vehicle_document_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicledocument",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="vehicle.vehicle",
            ),
        ),
    ]
