# Generated by Django 6.0.3 on 2026-03-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0007_alter_vehicledocument_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicledocument",
            name="document_type",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
