# Generated by Django 6.0.3 on 2026-03-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0008_added_document_type_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicledocument",
            name="expiring_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
