# Generated by Django 6.0.3 on 2026-03-30 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0009_added_expired_at_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicledocument",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicledocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
