# Generated by Django 6.0.3 on 2026-03-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0001_created_driver_model"),
        ("vehicle", "0010_added_timestamp_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="driver",
            field=models.ManyToManyField(related_name="vehicles", to="driver.driver"),
        ),
        migrations.AlterField(
            model_name="vehicledocument",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
