# Generated by Django 6.0.3 on 2026-04-05 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0011_created_driver_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicledocument",
            name="file",
            field=models.FileField(
                upload_to="vehicle/documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "docx",
                            "txt",
                            "xlsx",
                        ]
                    )
                ],
            ),
        ),
    ]
