# Generated by Django 6.0.3 on 2026-04-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0001_created_driver_model"),
        ("vehicle", "0012_created_ride_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="driver",
            field=models.ManyToManyField(
                blank=True, related_name="vehicles", to="driver.driver"
            ),
        ),
    ]
