# Generated by Django 6.0.3 on 2026-04-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0013_alter_vehicle_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Car"), (2, "Van"), (3, "Mini Bus"), (4, "Bus")],
                default=4,
                max_length=100,
            ),
        ),
    ]
