# Generated by Django 6.0.3 on 2026-04-09 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_company_options"),
        ("vehicle", "0014_alter_vehicle_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="company",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Car"), (2, "Van"), (3, "Mini Bus"), (4, "Bus")],
            ),
        ),
    ]
