# Generated by Django 6.0.3 on 2026-04-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0015_created_guide_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Car"),
                    (2, "Van"),
                    (3, "Mini Bus"),
                    (5, "Midi Bus"),
                    (4, "Bus"),
                ],
            ),
        ),
    ]
