# Generated by Django 6.0.3 on 2026-05-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.PositiveIntegerField(
                choices=[(100, "Admin"), (200, "Driver")], default=100
            ),
        ),
    ]
