# Generated by Django 6.0.3 on 2026-05-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="raw_password",
            field=models.CharField(
                blank=True,
                help_text="Only storing password from read only related objects that are created by admins.",  # noqa: E501
                max_length=50,
            ),
        ),
    ]
