# Generated by Django 6.0.3 on 2026-05-05 13:16

import common.models
import django.core.validators
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DriverDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("document_type", models.CharField(blank=True, max_length=255)),
                ("expiring_at", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="drivers/documents",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "docx",
                                    "txt",
                                    "xlsx",
                                ]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, common.models.DocumentManager),
            managers=[
                ("expiring", django.db.models.manager.Manager()),
            ],
        ),
    ]
