# Generated by Django 6.0.3 on 2026-05-05 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("driver", "0001_initial"),
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user_auth.user",),
        ),
        migrations.AddField(
            model_name="driverdocument",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_documents",
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="driverdocument",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="driver.driver",
            ),
        ),
    ]
