# Generated by Django 6.0.3 on 2026-04-09 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_company_options"),
        ("driver", "0001_created_driver_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="company.company",
            ),
        ),
    ]
