# Generated by Django 6.0.3 on 2026-04-28 10:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0002_alter_driver_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("document_type", models.CharField(blank=True, max_length=255)),
                ("expiring_at", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="drivers/documents",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "docx",
                                    "txt",
                                    "xlsx",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="driver.driver",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
