# Generated by Django 6.0.3 on 2026-04-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_driver_document_model"),
        ("driver", "0003_driver_document_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverdocument",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_documents",
                to="company.company",
            ),
        ),
    ]
