# Generated by Django 6.0.3 on 2026-05-02 12:36

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0004_document_company_relation"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="driverdocument",
            managers=[
                ("expiring", django.db.models.manager.Manager()),
            ],
        ),
    ]
